Aion/Areas/Admin/Controllers/ROIDashboardController.cs
using Aion.Areas.Admin.ViewModels.Shared;
using Aion.Attributes;
using Aion.Controllers;
using Aion.Models.Shared;
using Aion.DAL.Managers;
using PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Aion.Areas.Admin.Controllers
{
    [UserFilter(MinLevel = 9)]
    public class ROIDashboardController : BaseController
    {
        private readonly IAdminDashManager _dashManager;

        public ROIDashboardController()
        {
            _dashManager = new ROIDashManager();
        }

        public async Task<ActionResult> Index()
        {
            if (TempData["PackageRunning"] != null)
            {
                ViewBag.PackageRunning = true;
            }

            DashboardErrors vm = new DashboardErrors();
            vm.RoleErrors = await _dashManager.GetRoleErrors();
            vm.StoreErrors = await _dashManager.GetStoreErrors();

            return View(vm);
        }

        //Run sp to build dashboard with existing timecard data file
        public ActionResult RunBuild()
        {
            TempData["PackageRunning"] = _dashManager.RunBuild();

            return RedirectToAction("Index");
        }

        //Run sp to build dashboard with new timecard data file
        public ActionResult RunBuildNewData()
        {
            TempData["PackageRunning"] = _dashManager.RunBuildNewData();
            return RedirectToAction("Index");
        }

        //Run sp to import and update budgets from file
        public ActionResult RunBudgets()
        {
            TempData["PackageRunning"] = _dashManager.RunBudgets();
            return RedirectToAction("Index");
        }

        //Run sp to import and update budgets from file
        public ActionResult PushData()
        {
            TempData["PackageRunning"] = _dashManager.PushData();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> StoreList(int? page, string searchString)
        {
            var result = mapper.Map<List<StoreReferenceView>>(await _dashManager.StoreReferenceList());

            if (!string.IsNullOrEmpty(searchString))
            {
                int numVal = int.Parse(searchString);
                result = result.Where(x => x.Br_ == numVal).ToList();
            }

            int pageSize = 50;
            int pageNumber = page ?? 1;

            return View(result.ToPagedList(pageNumber, pageSize));
        }

        //add new storereference record
        public ActionResult AddStore(string SeedNumber)
        {
            ViewBag.SeedNumber = SeedNumber;
            return View();
        }

        //post new storereference record
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddStore(StoreReferenceView model)
        {
            if (ModelState.IsValid)
            {
                await _dashManager.SubmitNewStoreReference(model);
            }
            return RedirectToAction("StoreList");
        }

        //get storereference record for edit
        public async Task<ActionResult> EditStore(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            StoreReferenceView storeReference = mapper.Map<StoreReferenceView>(await _dashManager.StoreReferenceSingle(id));
            if (storeReference == null)
            {
                return HttpNotFound();
            }

            return View(storeReference);
        }

        //post changes to storereference record
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditStore(StoreReferenceView model)
        {
            if (ModelState.IsValid)
            {
                await _dashManager.SubmitStoreReferenceChange(model);
            }
            return RedirectToAction("Index");
        }

        //get storereference record for confirm delete
        public async Task<ActionResult> DeleteStore(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            StoreReferenceView storeReference = mapper.Map<StoreReferenceView>(await _dashManager.StoreReferenceSingle(id));
            if (storeReference == null)
            {
                return HttpNotFound();
            }

            return View(storeReference);
        }

        //post delete storereference record
        [HttpPost, ActionName("DeleteStore")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteStoreConfirmed(int id)
        {
            await _dashManager.DeleteStoreReferenceRecord(id);

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> RoleList()
        {
            return View(mapper.Map<List<RoleReferenceView>>(await _dashManager.RoleReferenceList()));
        }

        //add new rolereference record
        public ActionResult AddRole(string SeedRole)
        {
            ViewBag.SeedRole = SeedRole;
            return View();
        }

        //post new rolereference record
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddRole(RoleReferenceView model)
        {
            if (ModelState.IsValid)
            {
                await _dashManager.SubmitNewRoleReference(model);
            }
            return RedirectToAction("RoleList");
        }

        //get rolereference record for edit
        public async Task<ActionResult> EditRole(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RoleReferenceView roleReference = mapper.Map<RoleReferenceView>(await _dashManager.RoleReferenceSingle(id));
            if (roleReference == null)
            {
                return HttpNotFound();
            }

            return View(roleReference);
        }

        //post changes to rolereference record
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditRole(RoleReferenceView model)
        {
            if (ModelState.IsValid)
            {
                await _dashManager.SubmitRoleReferenceChange(model);
            }
            return RedirectToAction("RoleList");
        }

        //get rolereference record for confirm delete
        public async Task<ActionResult> DeleteRole(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RoleReferenceView roleReference = mapper.Map<RoleReferenceView>(await _dashManager.RoleReferenceSingle(id));
            if (roleReference == null)
            {
                return HttpNotFound();
            }

            return View(roleReference);
        }

        //post delete rolereference record
        [HttpPost, ActionName("DeleteRole")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteRoleConfirmed(string id)
        {
            await _dashManager.DeleteRoleReferenceRecord(id);

            return RedirectToAction("Index");
        }
    }
}

Aion/Areas/Admin/Views/ROIDashboard/AddRole.cshtml
@model Aion.Models.Shared.RoleReferenceView

@{
    ViewBag.Title = "Add Role";
}

<h2>Add Role</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <h4>Role Reference</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group form-row">
        @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control", Value = ViewBag.SeedRole } })
            @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Reporting_Role_Flag, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Reporting_Role_Flag, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Reporting_Role_Flag, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Sales_Role_Flag, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Sales_Role_Flag, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sales_Role_Flag, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <input type="submit" value="Create" class="btn btn-lg btn-success" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "RoleList")
</div>

Aion/Areas/Admin/Views/ROIDashboard/AddStore.cshtml
@model Aion.Models.Shared.StoreReferenceView

@{
    ViewBag.Title = "Add Store";
}

<h2>Add Store</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <h4>Store Reference</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group form-row">
        @Html.LabelFor(model => model.Br_, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Br_, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Br_, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.UK_BR, htmlAttributes: new { @class = "col-form-label col-2", Value = ViewBag.SeedNumber })
        <div class="col-10">
            @Html.EditorFor(model => model.UK_BR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UK_BR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Store_Name, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Store_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Store_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Division, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Division, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Division, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Region_name, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Region_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Region_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Channel, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Channel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Channel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <input type="submit" value="Create" class="btn btn-lg btn-success" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "StoreList")
</div>

Aion/Areas/Admin/Views/ROIDashboard/DeleteRole.cshtml
@model Aion.Models.Shared.RoleReferenceView

@{
    ViewBag.Title = "Delete Role";
}

<h2>Delete Role</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Role Reference</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reporting_Role_Flag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reporting_Role_Flag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sales_Role_Flag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sales_Role_Flag)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "RoleList")
        </div>
    }
</div>

Aion/Areas/Admin/Views/ROIDashboard/DeleteStore.cshtml
@model Aion.Models.Shared.StoreReferenceView

@{
    ViewBag.Title = "Delete Store";
}

<h2>Delete Store</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Store Reference</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UK_BR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UK_BR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Store_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Store_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Division)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Division)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Channel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Channel)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "StoreList")
        </div>
    }
</div>

Aion/Areas/Admin/Views/ROIDashboard/EditRole.cshtml
@model Aion.Models.Shared.RoleReferenceView

@{
    ViewBag.Title = "Edit Role";
}

<h2>Edit Role</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <h4>Role Reference</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control ", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Reporting_Role_Flag, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Reporting_Role_Flag, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Reporting_Role_Flag, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Sales_Role_Flag, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Sales_Role_Flag, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sales_Role_Flag, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <input type="submit" value="Save" class="btn btn-lg btn-success" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "RoleList")
</div>

Aion/Areas/Admin/Views/ROIDashboard/EditStore.cshtml
@model Aion.Models.Shared.StoreReferenceView

@{
    ViewBag.Title = "Edit Store";
}

<h2>Edit Store</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <h4>Store Reference</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Br_)

    <div class="form-group form-row">
        @Html.LabelFor(model => model.UK_BR, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.UK_BR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UK_BR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Store_Name, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Store_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Store_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Division, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Division, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Division, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Region_name, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Region_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Region_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-row">
        @Html.LabelFor(model => model.Channel, htmlAttributes: new { @class = "col-form-label col-2" })
        <div class="col-10">
            @Html.EditorFor(model => model.Channel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Channel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <input type="submit" value="Save" class="btn btn-lg btn-success" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "StoreList")
</div>

Aion/Areas/Admin/Views/ROIDashboard/Index.cshtml
@model Aion.Areas.Admin.ViewModels.Shared.DashboardErrors

@{
    ViewBag.Title = "ROI Dash";
}

<div class="container-fluid">
    <h2>ROI Dashboard Maintenance</h2>
    @if(ViewBag.PackageRunning != null)
    {
        <div class="alert alert-success text-center">
            The job has been started and should take no more than 1 minute to complete.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>            
        </div>
    }

    <img src="~/Images/Animated-Flag-Ireland.gif" />

    @if (Model.RoleErrors.Count() > 0 || Model.StoreErrors.Count() > 0)
    {
        <div class="card card-danger mb-3">
            <div class="card-header"><strong>There are errors present in the reference tables!</strong></div>
            <div class="card-body">
                @if (Model.RoleErrors.Count() > 0)
                {
                    <p>The following unmatched roles exist:</p>
                    <ul>
                        @foreach (var r in Model.RoleErrors)
                    {
                            <li>@r.ToString() - <a href="@Url.Action("AddRole","ROIDashboard",new { SeedRole=r.ToString() })">Add</a></li>
                        }
                    </ul>
                }
                @if (Model.StoreErrors.Count() > 0)
                {
                    <p>The following unmatched stores exist:</p>
                    <ul>
                        @foreach (var r in Model.StoreErrors)
                    {
                            <li>@r.ToString() - <a href="@Url.Action("AddStore","ROIDashboard",new { SeedNumber=r.ToString() })">Add</a></li>
                        }
                    </ul>
                }
            </div>
        </div>
    }
    <div>
        <a class="btn btn-primary" href="@Url.Action("RoleList", "ROIDashboard")">Role Reference</a>
    </div>
    <br />
    <div>
        <a class="btn btn-primary" href="@Url.Action("StoreList", "ROIDashboard")">Store Reference</a>
    </div>
    <br />
    <div>
        <a class="btn btn-success" href="@Url.Action("RunBudgets","ROIDashboard")">Import Budget Data</a>
    </div>
    <br />
    <hr />
    <div>
        <a class="btn btn-success" href="@Url.Action("RunBuild","ROIDashboard")">Re-Run Data Build</a>
    </div>
    <br />
    <div>
        <a class="btn btn-success" href="@Url.Action("RunBuildNewData","ROIDashboard")">Re-Run Data Build with new data</a>
    </div>
    <br />
    <hr />
    <div>
        <a id="pushBtn" class="btn btn-success" href="@Url.Action("PushData","ROIDashboard")">Push data to site</a><span class="text-danger pl-2"><strong>Only press when dashboard data has been validated</strong></span>
    </div>
</div>

Aion/Areas/Admin/Views/ROIDashboard/RoleList.cshtml
@model List<Aion.Models.Shared.RoleReferenceView>
@{
    ViewBag.Title = "Role List";
}

<h2>Role List</h2>

<p>@Html.ActionLink("Create New", "AddRole")</p>

<table class="table table-sm text-center">
    <thead>
        <tr>
            <th>Role</th>
            <th>Reporting Role Flag</th>
            <th>Sales Role Flag</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Role</td>
                <td>@item.Reporting_Role_Flag</td>
                <td>@item.Sales_Role_Flag</td>
                <td>
                    @Html.ActionLink("Edit", "EditRole", new { id = item.Role }) |
                    @Html.ActionLink("Delete", "DeleteRole", new { id = item.Role })
                </td>
            </tr>
        }
    </tbody>
</table>
<br />

@Html.ActionLink("Back", "Index", "ROIDashboard")

Aion/Areas/Admin/Views/ROIDashboard/StoreList.cshtml
@model PagedList.IPagedList<Aion.Models.Shared.StoreReferenceView>
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Store List";
}

<h2>Store Reference List</h2>

@using (Html.BeginForm())
{
    <p>
        Find by store number: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

<p>@Html.ActionLink("Create New", "AddStore")</p>

<table class="table table-sm text-center">
    <thead>
        <tr>
            <th>Store Number</th>
            <th>UK BR</th>
            <th>Store Name</th>
            <th>Division</th>
            <th>Region</th>
            <th>Region Name</th>
            <th>Channel</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Br_</td>
                <td>@item.UK_BR</td>
                <td>@item.Store_Name</td>
                <td>@item.Division</td>
                <td>@item.Region</td>
                <td>@item.Region_name</td>
                <td>@item.Channel</td>
                <td>
                    @Html.ActionLink("Edit", "EditStore", new { id = item.Br_ }) |
                    @Html.ActionLink("Delete", "DeleteStore", new { id = item.Br_ })
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("StoreList", new { page }))

@Html.ActionLink("Back", "Index", "UKDashManager")